### ISSUE TITLE
HW 01: TODO list

### ISSUE THREAD

**Issue by AlexVanGogen** [AlexVanGogen/spbau-java-course#1]
- [x] implement all
- [x] test on read words-based dictionary
- [x] delete unnecessary fields/methods
- [x] maybe rename some fields/methods
- [x] eat
